---
id: "140"
slug: "Unable to connect to server. Please check your net"
date: "2020-04-08"
title: "Unable to connect to server. Please check your network connectivity.- Network error"
---


## [#140](https://github.com/shridhar-tl/jira-assistant/issues/140) - Unable to connect to server. Please check your network connectivity.- Network error

### [manasa08april](https://github.com/manasa08april) commented on Apr 08, 2020

Below is the console error I am getting:
Chrome Browser service injected
4.984cd6c3.chunk.js:1 Deprecation warning: use moment.updateLocale(localeName, config) to change an existing locale. moment.defineLocale(localeName, config) should only be used for creating a new locale See http://momentjs.com/guides/#/warnings/define-locale/ for more info.
C @ 4.984cd6c3.chunk.js:1
index.html#/3/reports/userdaywise:1 Access to XMLHttpRequest at 'https://doc-10-3o-docs.googleusercontent.com/docs/securesc/mf32fo3qcla3d9hbqeq6drujiknbubke/s9sps1chhdpnrd3lln78b29vkfol912a/1583995650000/06806144531157585512/08304109166629802464/1aDFOfa5z5W5rP4ErvhMeAkYsq7-2_vk9?e=download&authuser=0' (redirected from 'https://drive.google.com/uc?export=download&id=1aDFOfa5z5W5rP4ErvhMeAkYsq7-2_vk9') from origin 'chrome-extension://momjbjbjpbcbnepbgkkiaofkgimihbii' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.
doc-10-3o-docs.googleusercontent.com/docs/securesc/mf32fo3qcla3d9hbqeq6drujiknbubke/s9sps1chhdpnrd3lln78b29vkfol912a/1583995650000/06806144531157585512/08304109166629802464/1aDFOfa5z5W5rP4ErvhMeAkYsq7-2_vk9?e=download&authuser=0:1 Failed to load resource: net::ERR_FAILED
index.1653008d.chunk.js:1 Unhandled rejection (promise:  Promise , reason:  Object ).
value @ index.1653008d.chunk.js:1
index.html#/3/reports/userdaywise:1 Uncaught (in promise) Object
DevTools failed to parse SourceMap: chrome-extension://momjbjbjpbcbnepbgkkiaofkgimihbii/static/js/4.984cd6c3.chunk.js.map
DevTools failed to parse SourceMap: chrome-extension://momjbjbjpbcbnepbgkkiaofkgimihbii/static/js/runtime~index.9e3cfb86.js.map
DevTools failed to parse SourceMap: chrome-extension://momjbjbjpbcbnepbgkkiaofkgimihbii/static/js/15.da193c71.chunk.js.map
DevTools failed to parse SourceMap: chrome-extension://momjbjbjpbcbnepbgkkiaofkgimihbii/static/js/index.1653008d.chunk.js.map
DevTools failed to parse SourceMap: chrome-extension://momjbjbjpbcbnepbgkkiaofkgimihbii/static/js/5.671720f5.chunk.js.map
DevTools failed to parse SourceMap: chrome-extension://momjbjbjpbcbnepbgkkiaofkgimihbii/static/js/16.4bcfcf1a.chunk.js.map
DevTools failed to parse SourceMap: chrome-extension://momjbjbjpbcbnepbgkkiaofkgimihbii/static/js/14.cbaa28f6.chunk.js.map
DevTools failed to parse SourceMap: chrome-extension://momjbjbjpbcbnepbgkkiaofkgimihbii/static/js/21.59a4f0ff.chunk.js.map
DevTools failed to parse SourceMap: chrome-extension://momjbjbjpbcbnepbgkkiaofkgimihbii/static/js/1.51fa9e58.chunk.js.map
DevTools failed to parse SourceMap: chrome-extension://momjbjbjpbcbnepbgkkiaofkgimihbii/static/js/33.0253e032.chunk.js.map
DevTools failed to parse SourceMap: chrome-extension://momjbjbjpbcbnepbgkkiaofkgimihbii/static/js/3.52bc2233.chunk.js.map
DevTools failed to parse SourceMap: chrome-extension://momjbjbjpbcbnepbgkkiaofkgimihbii/static/js/2.3ff5a883.chunk.js.map
DevTools failed to parse SourceMap: chrome-extension://momjbjbjpbcbnepbgkkiaofkgimihbii/static/js/0.dae74dcf.chunk.js.map

### [Tukks](https://github.com/Tukks) commented on Mar 13, 2020

Same here, with same stacktrace

### [shridhar-tl](https://github.com/shridhar-tl) commented on Mar 14, 2020

@manasa08april  @Tukks  - How long have you been using the extension without reinstalling? Have you ever reinstalled in past 2 months? If not then I would suggest you to uninstall and reinstall once and check. Their has been some updates in chrome which doesn't work for some users until they reinstall the extension.

If still it does not work, then I would like to know the version of chrome you are using. Also check the network tab and see if you have any errors in http request.

### [KirillZinchenko](https://github.com/KirillZinchenko) commented on Mar 17, 2020

Hi,

Same here. I just re-installed the extension and continue to get this error. 

Brave browser version 1.4.96 Chromium: 80.0.3987.132 (Official Build) (64-bit)

The extension v. 0.97

### [shridhar-tl](https://github.com/shridhar-tl) commented on Mar 19, 2020

@manasa08april @Tukks @KirillZinchenko - After reinstallation, while integrating with your jira, you should have got a dialog requesting for permission to access Jira. Did you git it? You should have allowed to access the site. If not then you will not be able to use it.

### [KirillZinchenko](https://github.com/KirillZinchenko) commented on Mar 19, 2020

Hi @shridhar-tl 

I have the dialog, but I still have the error. I just re-installed the extension again.

Thanks!

<img width="443" alt="Jira Assistant 1" src="https://user-images.githubusercontent.com/13957733/77047557-1d6cef00-69ef-11ea-92f6-25f13714ccd3.png">

<img width="308" alt="Jira Assistant 2" src="https://user-images.githubusercontent.com/13957733/77047564-2067df80-69ef-11ea-8cbb-c8c0077a6c6a.png"> 

Update: 

Here's the browser console log:

<img width="1426" alt="Jira Assistant 3" src="https://user-images.githubusercontent.com/13957733/77049497-61adbe80-69f2-11ea-98be-e5a3d08715fc.png">


### [eduardohf-ciandt](https://github.com/eduardohf-ciandt) commented on Mar 26, 2020

I have the same issue, any update on this?

### [shridhar-tl](https://github.com/shridhar-tl) commented on Mar 27, 2020

@eduardohf-ciandt, @KirillZinchenko - The error shown in the console screenshot is not related to your issue. This is related to issue with pulling of messages I send for all users. The issue specified in console log is already resolved couple of weeks back, but facing some issue in publishing the changes due to change in web store review process and more restriction which is detailed in #139 .

Will try to publish the changes within this weekend for chrome store and will update you the status.

But as I mentioned earlier in some other post, the issue with unable to connect is not reproducible by myself or any of my team members. Hence I had asked for output from network tab which I was still waiting for.

If possible for worklog related issue and this issue if someone was able to provide some test credentials for just a day, I would be able to solve this issue. But unfortunately, no one would be able to provide it as eveyone would be using the instance from their office. Hence I have no clue on what issue some people are facing. But I strongly feel this is something related to either some chrome settings or Jira settings a for most of the people this is working fine as expected.

### [KirillZinchenko](https://github.com/KirillZinchenko) commented on Mar 27, 2020

@shridhar-tl, I checked the Network tab while receiving the error and all requests have the status 200 or 302.

I am not a software developer, can you please point me what I need to check there to provide you more information? 

Also, I installed Google Chrome and tried that instead of the Brave browser and re-installed the extension there. Same error.



### [shridhar-tl](https://github.com/shridhar-tl) commented on Mar 27, 2020

@KirillZinchenko - I hope you have not used http url. You should use only https url. Can you let me know which request is giving 302?
Particularly I would like to know if request to any url in Jira is giving 302?

At the mean time I will try with Brave browser and see if I was able to reproduce it.

[Update] - I was not able to reproduce the issue with Brave browser as well. Can I know if you are using Cloud instance or Self hosted instance of Jira?

To analyse this issue further I would like to get someone's help. I will share a Cloud version of Jira test instance credentials and you can try and let me know if it is working for you or not. So that we can come to a conclusion whether the issue is with browser or with Jira instance and based on that I can proceed.

Whoever is interested please send a mail to me @ shridhar_tl@ymail.com. I will send an invite to you to use my instance of Jira and let us check.

### [KirillZinchenko](https://github.com/KirillZinchenko) commented on Mar 29, 2020

@shridhar-tl 

Hi,

We use Jira Cloud and it is using HTTPS by default.

These are two status 302 requests:

https://gist.github.com/KirillZinchenko/c586adb20fb08f27f2cf6ebe5a31a602
https://gist.github.com/KirillZinchenko/4dcfe40ccb1b68b39f36bf0e0d42c992

I will drop you an email to gain access to a Cloud version of Jira test instance.

Thank you. 


### [zhangzhecomiru](https://github.com/zhangzhecomiru) commented on Mar 30, 2020

same error


### [zhangzhecomiru](https://github.com/zhangzhecomiru) commented on Mar 30, 2020

![image](https://user-images.githubusercontent.com/55075595/77881367-cfcb6e80-7299-11ea-8e8d-2bc196f1a7a2.png)


### [shridhar-tl](https://github.com/shridhar-tl) commented on Mar 30, 2020

@zhangzhecomiru - As I mentioned earlier, this error and unable to connect message is completely ok. This error just means you could not pull the messages I send for all the users which is fine if it does not work. Will try to fix it in next release.

But have you tried to pull worklog report and check if it is working. Also check any other functionality you need is working fine. That is all what is needed. Please ignore the error in above snapshot for time being which would not case any issues to other functionalities.

### [zhangzhecomiru](https://github.com/zhangzhecomiru) commented on Apr 03, 2020

> @zhangzhecomiru - As I mentioned earlier, this error and unable to connect message is completely ok. This error just means you could not pull the messages I send for all the users which is fine if it does not work. Will try to fix it in next release.
> 
> But have you tried to pull worklog report and check if it is working. Also check any other functionality you need is working fine. That is all what is needed. Please ignore the error in above snapshot for time being which would not case any issues to other functionalities.

It seems other functions works fine.

Thank you for reply.


### [shridhar-tl](https://github.com/shridhar-tl) commented on Apr 03, 2020

@zhangzhecomiru - Thank you for confirming all the other functionalities are working. It means to me that other than seeing a error message you do not have any impact in any of the functionalities. If you face any issue, please feel free to report it.

@manasa08april  @KirillZinchenko  @eduardohf-ciandt @Tukks - Hope you too do not face any issue other than just an error message. If it is so, then I will close this issue. The error message which is getting displayed for some will get resolved soon. But no functionality will be impacted because of that.

### [KirillZinchenko](https://github.com/KirillZinchenko) commented on Apr 03, 2020

@shridhar-tl hi,

I wanted to test the issue using your testing Jira instance today. I will let you know if it's okay.

### [KirillZinchenko](https://github.com/KirillZinchenko) commented on Apr 03, 2020

@shridhar-tl hi,

I have the same error on your test Jira. 

### [shridhar-tl](https://github.com/shridhar-tl) commented on Apr 04, 2020

@KirillZinchenko - If you just see that error message please ignore it. Is any functionality getting impacted. For example, Is worklog report getting generated properly?

### [KirillZinchenko](https://github.com/KirillZinchenko) commented on Apr 06, 2020

@shridhar-tl, okay. Everything else works fine for me, the message is just annoying and sometimes block some buttons beneath it. 

Thanks. 

### [shridhar-tl](https://github.com/shridhar-tl) commented on Apr 08, 2020

Thank you for confirming. As everything else is working, closing this issue. The network error message will be fixed in next release as part of #136.
